<a href="https://colab.research.google.com/github/MalVaroTor/MalVaroTor/blob/main/Projeto_Minicurso_Python_Hashtag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio: importar uma base de dados do google drive, tratar seus dados e calcular o faturamento por loja, a quantidade de produtos por loja e o ticket médio, todos de forma tabular, com o maior valor em cima e o menor na parte de baixo.

In [8]:
# Passo 01: Importar a base de dados

import os 
import pandas as pd
import openpyxl                 # O "openpyxl" faz a ligação entre o python e 
                                # arquivos do tipo excel. Aqui no google colab 
                                # não é necessário porque já vem esta biblioteca.

tabela = pd.read_excel("/content/drive/MyDrive/CÓDIGOS E BANCO DE DADOS PARA OS CURSOS PYTHON/Minicurso Python Hashtag/Vendas.xlsx")

# pd.set_option("display.max_columns", None) # O "pd.set_option(opção, valor)", 
# o "display.max_columns" significa mostrar máximo de colunas. Já o "None" é nenhum, 
# pois ele é o limitador, se desejamos mostrar todas as colunas, então não queremos
# um máximo, e sim todas elas.

display(tabela)

# O Erro "UnicodeDecodeError" significa um erro no qual existe 
# caracteres aos quais o python não conhece, como o "ç" no português.

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
100995,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
100996,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
100998,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

>>> Na resposta acima se tem toda a tabela trazida do google drive.

Passo 02: Visualizar a base de dados

In [2]:
tabela = tabela[["ID Loja", "Produto", "Quantidade", "Valor Unitário", "Valor Final"]]

display(tabela)

,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,Iguatemi Esplanada,Camiseta,2,180,360
2,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,Norte Shopping,Relógio,3,200,600
4,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...
100994,Center Shopping Uberlândia,Short Listrado,2,102,204
100995,Center Shopping Uberlândia,Mochila,4,270,1080
100996,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
100997,Ribeirão Shopping,Camisa Listrado,1,108,108
100998,Ribeirão Shopping,Short Linho,2,133,266

>>> Na resposta acima tem-se a tabela de forma organizada, trazendo apenas as colunas desejas.

Passo 03: Calcular o faturamento por loja

In [3]:
tabela_fat = tabela.groupby("ID Loja").sum()
tabela_fat = tabela_fat[["Valor Final"]]
tabela_fat01 = tabela_fat
tabela_fat = tabela_fat[["Valor Final"]].sort_values(by="Valor Final", ascending=False)
display(tabela_fat)

                                  Valor Final
ID Loja
Iguatemi Campinas                     1762419
Shopping Vila Velha                   1731167
Bourbon Shopping SP                   1726110
Rio Mar Recife                        1722766
Shopping SP Market                    1721763
Palladium Shopping Curitiba           1721120
Norte Shopping                        1711968
Ribeirão Shopping                     1707122
Iguatemi Esplanada                    1699681
Rio Mar Shopping Fortaleza            1698430
Shopping Center Leste Aricanduva      1682870
Novo Shopping Ribeirão Preto          1678225
Shopping Iguatemi Fortaleza           1674824
Center Shopping Uberlândia            1668921
Shopping União de Osasco              1663770
Shopping Barra                        1653103
Passei das Águas Shopping             1649014
Shopping Eldorado                     1648111
Salvador Shopping                     1646739
Shopping Center Interlagos            1640486
Shopping Ibirapuera                   1635060
Parque Dom Pedro Shopping             1631630
Shopping Recife                       1624879
Shopping Midway Mall                  1590441
Shopping Morumbi                      1586444

>>> Na resposta acima temos a tabela de ID Loja e seu Valor Final, ou seja, uma tabela do Faturamento e a ordem descrescente dos valores de cima para baixo.

Passo 04: Calcular a quantidade de produtos vendidos por loja

In [4]:
tabela_qtd = tabela.groupby("ID Loja").sum()
tabela_qtd = tabela_qtd[["Quantidade"]]
tabela_qtd01 = tabela_qtd
tabela_qtd = tabela_qtd[["Quantidade"]].sort_values(by="Quantidade", ascending=False)
display(tabela_qtd)

                                  Quantidade
ID Loja
Shopping Vila Velha                     9224
Palladium Shopping Curitiba             9091
Norte Shopping                          9014
Shopping Center Leste Aricanduva        8938
Rio Mar Shopping Fortaleza              8937
Iguatemi Campinas                       8935
Shopping SP Market                      8927
Rio Mar Recife                          8863
Bourbon Shopping SP                     8863
Ribeirão Shopping                       8825
Novo Shopping Ribeirão Preto            8751
Shopping União de Osasco                8730
Shopping Ibirapuera                     8723
Shopping Eldorado                       8719
Salvador Shopping                       8698
Shopping Center Interlagos              8675
Shopping Barra                          8638
Shopping Iguatemi Fortaleza             8629
Center Shopping Uberlândia              8627
Passei das Águas Shopping               8618
Shopping Recife                         8581
Iguatemi Esplanada                      8580
Shopping Morumbi                        8508
Parque Dom Pedro Shopping               8388
Shopping Midway Mall                    8206

>>> Na resposta acima temos a tabela de ID Loja e sua Quantidade, ou seja, uma tabela da quantidade dos produtos vendidos e a ordem descrescente de cima para baixo.

Passo 05: Calcular o ticket médio por produto em cada loja

In [5]:
ticket_medio = (tabela_fat01["Valor Final"] / tabela_qtd01["Quantidade"]).to_frame()
# O "().to_frame()" faz com que os dados que estão jogados se tornem
# dados em uma tabela, pois quando se faz uma operação de uma coluna com outra, 
# os dados são gerados, mas não tabelados.

print("_" * 50) # Gera uma string de caracteres que estão dentro dos aspas e 
                # multiplica pela quantidade desejada.
display(ticket_medio)

__________________________________________________

                                           0
ID Loja
Bourbon Shopping SP               194.754598
Center Shopping Uberlândia        193.453228
Iguatemi Campinas                 197.248909
Iguatemi Esplanada                198.098019
Norte Shopping                    189.923231
Novo Shopping Ribeirão Preto      191.775226
Palladium Shopping Curitiba       189.321307
Parque Dom Pedro Shopping         194.519552
Passei das Águas Shopping         191.345324
Ribeirão Shopping                 193.441586
Rio Mar Recife                    194.377299
Rio Mar Shopping Fortaleza        190.044758
Salvador Shopping                 189.323868
Shopping Barra                    191.375666
Shopping Center Interlagos        189.105014
Shopping Center Leste Aricanduva  188.282614
Shopping Eldorado                 189.025232
Shopping Ibirapuera               187.442394
Shopping Iguatemi Fortaleza       194.092479
Shopping Midway Mall              193.814404
Shopping Morumbi                  186.464974
Shopping Recife                   189.357767
Shopping SP Market                192.871401
Shopping União de Osasco          190.580756
Shopping Vila Velha               187.680724

>>> Na resposta acima temos a tabela de ID Loja com seu valor de ticket médio em ordem descrescente dos valores de cima para baixo. Foi necessário a criação das variávies "tabela_fat01" e "tabela_qtd01" para manter a sequência dos dados na tabela, e assim foi possível a divisão correta dos dados de Faturamento pela sua Quantidade.

# Ordene os dados do ticket médio para melhor compreensão.

In [7]:
ticket_medio_ordem = ticket_medio[[0]].sort_values(by= 0, ascending=False)

display(ticket_medio_ordem)

                                           0
ID Loja
Iguatemi Esplanada                198.098019
Iguatemi Campinas                 197.248909
Bourbon Shopping SP               194.754598
Parque Dom Pedro Shopping         194.519552
Rio Mar Recife                    194.377299
Shopping Iguatemi Fortaleza       194.092479
Shopping Midway Mall              193.814404
Center Shopping Uberlândia        193.453228
Ribeirão Shopping                 193.441586
Shopping SP Market                192.871401
Novo Shopping Ribeirão Preto      191.775226
Shopping Barra                    191.375666
Passei das Águas Shopping         191.345324
Shopping União de Osasco          190.580756
Rio Mar Shopping Fortaleza        190.044758
Norte Shopping                    189.923231
Shopping Recife                   189.357767
Salvador Shopping                 189.323868
Palladium Shopping Curitiba       189.321307
Shopping Center Interlagos        189.105014
Shopping Eldorado                 189.025232
Shopping Center Leste Aricanduva  188.282614
Shopping Vila Velha               187.680724
Shopping Ibirapuera               187.442394
Shopping Morumbi                  186.464974

>>> Para finalizar, foi colocado em tabela o ticket médio de forma organizada, do maior valor no topo para o menor valor na parte de baixo.